name: lear-github-actions
on: [push, workflow_dispatch]
jobs:
  DEV:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  QA:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  UAT:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  PROD:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
